apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 2
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
      # annotations:
      #   kubernetes.io/change-cause: "cambio pblgllgs/hoobank:latest"
    spec:
      containers:
      - name: hello-world
        image: amigoscode/kubernetes:hello-world-v2
        # image: pblgllgs/hoobank:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
