apiVersion: v1
kind: Namespace
metadata:
  name: engineering
---
apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: Namespace
metadata:
  name: tooling
---
apiVersion: v1
kind: Namespace
metadata:
  name: ml